#!/usr/bin/env python3
# -*- mode: python; indent-tabs-mode: nil -*-

# Part of mlat-client - an ADS-B multilateration client.
# Copyright 2015, Oliver Jowett <oliver@mutability.co.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import socket

import mlat.client.version
import time

from mlat.client import util
from mlat.client.receiver import ReceiverConnection
from mlat.client.jsonclient import JsonServerConnection
from mlat.client.coordinator import Coordinator
from mlat.client import options


def check_receiver_availability(host, port, max_attempts=3, retry_delay=2):
    """Check if the receiver is available before starting the client.

    Returns True if receiver is reachable, False otherwise.
    """
    util.log('Checking receiver availability at {host}:{port}', host=host, port=port)

    for attempt in range(1, max_attempts + 1):
        try:
            test_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            test_socket.settimeout(3)
            test_socket.connect((host, port))
            test_socket.close()
            util.log('Receiver is available')
            return True
        except (socket.error, socket.timeout) as e:
            if attempt < max_attempts:
                util.log('Receiver not available (attempt {attempt}/{max_attempts}), retrying in {delay} seconds...',
                        attempt=attempt, max_attempts=max_attempts, delay=retry_delay)
                time.sleep(retry_delay)
            else:
                util.log('WARNING: Receiver at {host}:{port} is not available after {attempts} attempts',
                        host=host, port=port, attempts=max_attempts)
                util.log('WARNING: Please ensure your receiver (dump1090/readsb/etc.) is running and accessible')
                util.log('WARNING: The client will continue, but may not function properly until receiver is available')
                return False

    return False


def main():
    parser = argparse.ArgumentParser(description="Client for multilateration.")

    options.make_inputs_group(parser)
    options.make_results_group(parser)

    location = parser.add_argument_group('Receiver location')
    location.add_argument('--lat',
                          type=options.latitude,
                          help="Latitude of the receiver, in decimal degrees. Required.",
                          required=True)
    location.add_argument('--lon',
                          type=options.longitude,
                          help="Longitude of the receiver, in decimal degrees. Required.",
                          required=True)
    location.add_argument('--alt',
                          type=options.altitude,
                          help="""
Altitude of the receiver (height above ellipsoid).  Required. Defaults to metres, but units may
specified with a 'ft' or 'm' suffix. (Except if they're negative due to option
parser weirdness. Sorry!)""",
                          required=True)
    location.add_argument('--privacy',
                          help="""
Sets the privacy flag for this receiver. Currently, this removes the receiver
location pin from the coverage maps.""",
                          action='store_true',
                          default=False)

    server = parser.add_argument_group('Multilateration server connection')
    server.add_argument('--user',
                        help="User information to give to the server. Used to get in touch if there are problems.",
                        required=True)
    server.add_argument('--server',
                        help="host:port of the multilateration server to connect to",
                        type=options.hostport,
                        default=('feed.planespotters.net', 31090))
    server.add_argument('--no-udp',
                        dest='udp',
                        help="Don't offer to use UDP transport for sync/mlat messages",
                        action='store_false',
                        default=True)
    server.add_argument('--uuid-file',
                        dest='uuid_path',
                        help="Send the UUID in this file to the server",
                        required=False)

    logOptions = parser.add_argument_group('Log Options')
    logOptions.add_argument('--log-timestamps',
                          dest='log_timestamps',
                          help="Print timestamps in logging output",
                          action='store_true',
                          default=False)

    args = parser.parse_args()

    util.suppress_log_timestamps = not args.log_timestamps

    if abs(args.lat) < 0.1 and abs(args.lon) < 0.1:
        util.log("<3>Latitude / Longitude not set, please configure and reboot")
        time.sleep(3600)
        raise SystemExit

    util.log("mlat-client {version} starting up", version=mlat.client.version.CLIENT_VERSION)

    outputs = options.build_outputs(args)

    receiver = ReceiverConnection(host=args.input_connect[0], port=args.input_connect[1],
                                  mode=options.connection_mode(args))

    server = JsonServerConnection(host=args.server[0], port=args.server[1], uuid_path=args.uuid_path,
                                  handshake_data={'lat': args.lat,
                                                  'lon': args.lon,
                                                  'alt': args.alt,
                                                  'user': args.user,
                                                  'clock_type': options.clock_type(args),
                                                  'clock_frequency': options.clock_frequency(args),
                                                  'clock_epoch': options.clock_epoch(args),
                                                  'privacy': args.privacy},
                                  offer_zlib=True,
                                  offer_udp=args.udp,
                                  return_results=(len(outputs) > 0))

    coordinator = Coordinator(receiver=receiver, server=server, outputs=outputs, freq=options.clock_frequency(args),
                              allow_anon=args.allow_anon_results, allow_modeac=args.allow_modeac_results)

    # Check receiver availability before starting
    check_receiver_availability(args.input_connect[0], args.input_connect[1])

    # Start receiver connection first to give it time to establish before server handshake
    util.log('Connecting to receiver at {host}:{port}', host=args.input_connect[0], port=args.input_connect[1])
    receiver.reconnect()

    # Start server connection
    server.start()
    try:
        coordinator.run_forever()
    except KeyboardInterrupt:
        util.log('Keyboard interrupt, shutting down')
    except Exception as e:
        util.log('Unexpected exception: {0}', e)
        raise

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
    except Exception:
        import traceback
        traceback.print_exc()
        raise SystemExit(1)
